name: 🚀🔥 Publish Package (dataloom)
on:
  release:
    types: [published]

concurrency: ${{ github.workflow}}-${{github.ref}}

jobs:
  build:
    name: 🚀🚀 Building the Package
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: 🚀 Checkout Github Repository
        uses: actions/checkout@v2
      - name: 🚀 Setup Node and NPM
        uses: actions/setup-node@v2
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
      - name: 🚀 Installing Packages using Yarn
        run: yarn install
      - name: 🚀 Linting and building
        run: yarn lint && yarn build
      - name: 🚀 Publish package on NPM 📦
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
